### ISSUE TITLE
ฺBug report

### ISSUE THREAD

**Issue by AuJUngZ** [AuJUngZ/PASTY_Project#8]
### **ทุกฟังก์ชันที่มีการเลือกตัวเลือก**

เวลาเรากรอก input แบบไม่ใช่ตัวเลขเข้าไปทำให้โปรแกรมทำงานไม่ปกติ

```
`if(Choice == 1){
        system("cls");
        MainMenu_Student();
    }else if(Choice == 2){
        system("cls");
        MainMenu_Admin();
    }else if(Choice == 3){
        exit(0);
    }else{
        cout<<"\n\t\tPlease enter correct option :(";
        cin.get();
        system("CLS");
        Select_role();
    }
```

น่าจะมาจาก code ตรงนี้นะเพราะเหมือนๆกันทุกอันเลย ลองใช้เป็น switch/case ดูน่าจะช่วยแก้ได้

**Comment by Suchark** [comment]
เปลี่ยนเป็น switch/case แล้วนะ แต่เหมือนจะยังติดบัคอยู่ ถ้าเกิดพิมพ์ตัวหลังสือไปมันไม่กระพริบแล้วแต่มันทำงานต่อไม่ได้ ไม่รู้เป็นที่โปรกแกรมเราเอ๋อป่าว รบกวนฝากอู๋ pull รันดูอีกทีนะ

**Comment by PlubCPE** [comment]
แก้แล้วคับ ลองเทสด้วยการกรอกตัวอื่นไปที่ไม่ใช่ตัวเลขปรากฎว่ายังทำงานได้ปกติคับผม
